#!/bin/bash

# GET request
#curl http://127.0.0.1:5000/api/tasks 

# POST request
curl -X POST -H "Content-Type: application/json" -d "{\"name\": \"task 1\", \"description\": \"description of task 1\", \"status\": \"ADDED\"}" http://90.156.230.242:5000/api/task
curl -X POST -H "Content-Type: application/json" -d "{\"name\": \"task 2\", \"description\": \"description of task 2\", \"status\": \"ADDED\"}" http://90.156.230.242:5000/api/task
curl -X POST -H "Content-Type: application/json" -d "{\"name\": \"task 3\", \"description\": \"description of task 3\", \"status\": \"ADDED\"}" http://90.156.230.242:5000/api/task
curl -X POST -H "Content-Type: application/json" -d "{\"name\": \"task 4\", \"description\": \"description of task 4\", \"status\": \"ADDED\"}" http://90.156.230.242:5000/api/task
curl -X POST -H "Content-Type: application/json" -d "{\"name\": \"task 5\", \"description\": \"description of task 5\", \"status\": \"ADDED\"}" http://90.156.230.242:5000/api/task
# PUT request
#curl -X PUT -H "Content-Type: application/json" -d '{"key": "new_value"}' https://api.example.com/data/123

# DELETE request
#curl -X DELETE https://api.example.com/data/123

