#!/bin/bash

# GET request
curl http://127.0.0.1:5000/api/tasks 

# POST request
#curl -X POST -H "Content-Type: application/json" -d '{"key": "value"}' https://api.example.com/data

# PUT request
#curl -X PUT -H "Content-Type: application/json" -d '{"key": "new_value"}' https://api.example.com/data/123

# DELETE request
#curl -X DELETE https://api.example.com/data/123

